### ISSUE TITLE
Customizable Template Urls

### ISSUE THREAD

**Issue by remmeier** [khan4019/tree-grid-directive#10]
the following code could be used to make the template url customizable:

templateUrl: function(element, attr) { return attr.templateUrl ? attr.templateUrl : 'defaul-template-url.html' },
        
Regards

**Comment by diosney** [comment]
+1

**Comment by diosney** [comment]
@remmeier If you need this functionality you can use the fork at https://github.com/diosney/tree-grid-directive until its merged into the main repo.

**Comment by khan4019** [comment]
merge done
