### ISSUE TITLE
Must update tree-grid-directive version when "bower install"

### ISSUE THREAD

**Issue by zweeen** [khan4019/tree-grid-directive#100]
Hi, very nice directive  thx a lot :)

Just wanted to say that the bower version of "tree-grid-directive" isn't the same than the github version.

Good luck and thx angain

**Comment by TrueDub** [comment]
I've created a new version, released it on Github and on NPM, but I cannot release it on bower as there is already a version with that name there, from another repo, and we cannot overwrite. 

This would need to be unregistered, according to the instructions at https://github.com/bower/bower/issues/120 - but it would need to be done by the maintainer, who is @okigan .

**Comment by okigan** [comment]
I'll coordinate with you, I'll check in later today

**Comment by okigan** [comment]
Ok, the fixes I needed in tree-grid-directive were incorporated back into this repo -- so I am fine if you'll start publishing from here to bower.

I delete the project from bower (once I find the token it is asking for)

**Comment by TrueDub** [comment]
Any luck, @okigan? Thanks for your cooperation.

**Comment by okigan** [comment]
it is (supposedly done), output when I re-ran the delete command: 

 curl -v -X DELETE "https://bower.herokuapp.com/packages/angular-bootstrap-grid-tree?access_token=441be92fdbc29c15b825f7"
*   Trying 50.17.253.252...
* Connected to bower.herokuapp.com (50.17.253.252) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: *.herokuapp.com
* Server certificate: DigiCert SHA2 High Assurance Server CA
* Server certificate: DigiCert High Assurance EV Root CA
> DELETE /packages/angular-bootstrap-grid-tree?access_token=4412fdbc29c15b825f7 HTTP/1.1
> Host: bower.herokuapp.com
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Server: Cowboy
< Connection: keep-alive
< Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
< Access-Control-Allow-Methods: GET,POST
< Access-Control-Allow-Origin: *
< Content-Length: 17
< Content-Type: text/html; charset=utf-8
< Date: Fri, 27 May 2016 17:01:13 GMT
< Etag: W/"11-QHu81pkvqY4GDiPgKlizxw"
< Vary: Accept-Encoding
< X-Powered-By: Express
< Via: 1.1 vegur
< 
* Connection #0 to host bower.herokuapp.com left intact

**Comment by TrueDub** [comment]
I can't find it in a search, which would indicate it's been deleted, I'll attempt to release a new version to both NPM and Bower now. Thanks for your help @okigan

**Comment by TrueDub** [comment]
OK, this directive, from version 0.3.0, is now available on Bower and on NPM. Closing this issue.

**Comment by zweeen** [comment]
Well done guys thx :)
