### ISSUE TITLE
Add a non field widget

### ISSUE THREAD

**Issue by dmalisani** [khan4019/tree-grid-directive#103]
I need add a checkbox and others widget (buttons, etc) but it should appears only when the branch is expanded. This mean, It must be visible only for each children item.
How I can do it?

**Comment by khan4019** [comment]
Change the template. Something similar to inside <li ng-repeat
````
<label>  <input ng-click=\"checkChanged(row)\" type=\"checkbox\" ng-model=\"row.isSelected\">{{ row.label }}</label>
````

**Comment by dmalisani** [comment]
yes.. I already tried it
but this method it shows in each row, not only in children
---template (partial)----
 <td ng-repeat="col in colDefinitions">
     <div ng-if="col.cellTemplate" compile="col.cellTemplate"></div>
    <div ng-if="!col.cellTemplate">{{row.branch[col.field]}}</div>
         <input ng-click="checkChanged(row)" type="checkbox" ng-model="row.isSelected"></label>
  </td>

**Comment by khan4019** [comment]
use ng-if in input tag when row.children is null

**Comment by dmalisani** [comment]
it works (with row.branch). Thanks a lot!

**Comment by khan4019** [comment]
Can you share the changes you made for this? This will help others for similar use case. Some plunker will be awesome

**Comment by dmalisani** [comment]
The pertinent part in my template is:
```
<td ng-repeat="col in colDefinitions">
    <div ng-if="col.cellTemplate" compile="col.cellTemplate"></div>
    <div ng-if="!col.cellTemplate">{{row.branch[col.field]}}</div>
             <input ng-if="!row.branch.children.length" ng-click="checkChanged(row)" type="checkbox"    ng-model="row.isSelected"></label>
 </td>
```
