### ISSUE TITLE
Documentation clarification

### ISSUE THREAD

**Issue by dallincoons** [khan4019/tree-grid-directive#110]
What does this mean? Can you provide an example where this is used?

"**expanding_property**: this is the property of the objects in tree_data where you want to put the ability to expand and collapse. This accepts an array of the same format as col_defs, allowing for sorting & filtering on the expanding field. This now includes the ability to provide a cellTemplate (but not a cellTemplateScope)."

**Comment by TrueDub** [comment]
I'm glad you edited your question.

To answer:

To allow your tree to expand and collapse, you must specify a field to be the one that controls this.  Looking at our [example page](http://khan4019.github.io/tree-grid-directive/test/treeGrid.html) you can see that the Name field is the expanding property.

The expanding_property object is of the same format as the col_defs one, with fields to control sorting & filtering. You may also provide a template for the appearance of this field.

**Comment by dallincoons** [comment]
For the record, here's what I edited out:

"This writing is nonsensical."

Ooooh scary.

**Comment by TrueDub** [comment]
Actually, you edited out "this is non-nonsensical". 

I'm assuming your query has been answered, so I'll close this issue. Feel free to ask any other questions you may have.

**Comment by dallincoons** [comment]
Whoever wrote it sucks at writing.
