### ISSUE TITLE
offically maintained on npm?

### ISSUE THREAD

**Issue by kennynaoh** [khan4019/tree-grid-directive#116]
Hello @khan4019 ,
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
And we prefer to use [npm](https://www.npmjs.com/package/angular-bootstrap-grid-tree) than git repo.
Please help me confirm that whether this library is officially maintained on npm.
Thanks for your help!

https://github.com/cdnjs/cdnjs/issues/9478

**Comment by TrueDub** [comment]
Yes it is - see https://www.npmjs.com/package/angular-bootstrap-grid-tree

**Comment by kennynaoh** [comment]
Thanks @TrueDub
