### ISSUE TITLE
< table> in default template is not closed

### ISSUE THREAD

**Issue by okigan** [khan4019/tree-grid-directive#12]

**Comment by diosney** [comment]
It seems that this is fixed now since I don't see the bug in the template.

**Comment by okigan** [comment]
i think you already pulled a request from me that fixed that -- so close this as duplicate

**Comment by diosney** [comment]
Yes, it seems so. I'm planning to send a push request as soon as I fix another bug hopefully its get added soon :)

@khan4019 BTW, are you supporting this repo yet? It seems that it has been a while since the last commit.

**Comment by khan4019** [comment]
I didnt updated anything for a while. However, i merged ur last fixes. So, if you have updates, feel free to push changes and I will merge them

**Comment by diosney** [comment]
Thanks for the merge :smile:
