### ISSUE TITLE
Icon mouseover funcitonality

### ISSUE THREAD

**Issue by nicknlsn** [khan4019/tree-grid-directive#134]
Is it possible to have a mouseover tooltip for the leaf icon? The items I have in the tree grid are files, and I want the modified time for each file to show in a text popup/tooltip when hovering over the leaf icon. I've been trying to figure out a way to do with but haven't figured it out.

Edit: I've been able to get this to work by customizing the tree-grid-directive.js file, but I would like to be able to do this without changing that file.

**Comment by torsten-sauer** [comment]
Maybe you can use a modified template? This is supported and should do the trick. Changing the template is quite easy, head for the part with `ng-class="row.tree_icon"` - there you can insert your tooltip logic for the icons.

If you try to add tooltips to the cell values, you should use the corresponding cell template.

**Comment by nicknlsn** [comment]
Thanks @torsten-sauer! That worked for me. I was a little confused at first because of where tree-drig-directive.js was being included from in our app, but I was able to move things around and it's working great now.
