### ISSUE TITLE
The expand/ collapse is not accessible via keyboard

### ISSUE THREAD

**Issue by sadiksha** [khan4019/tree-grid-directive#135]
Hi,
Right now I can expand or collapse a tree only with mouse. The expand/collapse is not accessible with keyboard. For instance, if I add tabindex on the link, the selection is visible but when I press enter, nothing happens.

**Comment by torsten-sauer** [comment]
The expand links in the default template are with `ng-click` - so maybe this is the reason enter doesn't work for you out of the box.

I think you need to change the template and add `ng-keypress` to the links to get this working.

**Comment by sadiksha** [comment]
Hi @torsten-sauer , thank you for the comment, I tried ng-keypress and it works great. Thank you.

**Comment by torsten-sauer** [comment]
Great to hear, maybe you can close this issue as it seems resolved, or?
