### ISSUE TITLE
How to load dynamic tree from REST

### ISSUE THREAD

**Issue by cwichoski** [khan4019/tree-grid-directive#14]
Hi, 

appears that only work with fixed tree, how I can load the tree dynamically from REST? And update that tree with new REST requests?

Thanks for any help.

**Comment by aidanlister** [comment]
Oh dynamic data is really important and I can't get graywolf's version to work. Is someone able to update this?

**Comment by kpnigalye** [comment]
try using 'promise' feature by angular. That worked for me.

**Comment by aidanlister** [comment]
I got graywolf366's going. I also made an example on Plunkr, and showed how you can customise the template without changing the directive source:
http://plnkr.co/edit/bxejGsjMg3MaqnYcHKze?p=preview

**Comment by diosney** [comment]
@aidanlister I' m trying to see your plnkr but for some reason its giving me trouble to acces it.

Please, can you post the sample code to other place so I can see it? It doesn't have to be a live site, just the code (pastebin or another one could work).

Thanks in advance.

**Comment by aidanlister** [comment]
There's too much code, the plunkr seems to work for me in incognito?

**Comment by diosney** [comment]
@aidanlister That was for no use :( It simple doesn't load for me.

Nevertheless, I did I understand now, is it loading the whole data at a later moment using promises, right?

**Comment by aidanlister** [comment]
Try a different browser or device then...

**Comment by diosney** [comment]
I did that and didn't worked.

Don't worry, @graywolf336 already answered me clarifying about the changes he made to the module.

**Comment by diosney** [comment]
@khan4019 You can closed this issue too, its already merged and included in the README.

**Comment by khan4019** [comment]
Awesome... thanks a lot... @diosney

**Comment by neran27** [comment]
Hi All,

For dynamic data / REST binding.,

if (myTreeData.length == 0) {
            dataMiningFactory.getTreeData().success(function (data) {
                rawTreeData = data;
                myTreeData = getTree(rawTreeData, 'DemographicId', 'ParentId');
            });
            $timeout(function () {
                $scope.tree_data = myTreeData;
            }, 5000);
        }

This will do the purpose for me, but only when the tree alone is added in the page. But when integrated with other HTML elements, the data is returned but tree is not updated on the UI. :(
