### ISSUE TITLE
Adding image in a cell template

### ISSUE THREAD

**Issue by RishiChowdaryPentyala** [khan4019/tree-grid-directive#24]

**Comment by diosney** [comment]
+1 to this.

**Comment by diosney** [comment]
@RishiChowdaryPentyala Why you closed the issue? Did you made it to work? If it is, please, can you share the solution?

Thanks

**Comment by diosney** [comment]
@khan4019 This new feature is already added in the new PR :)

Support for custom templates was added, being images or any custom HTML with any Angular directives.
