### ISSUE TITLE
Issue in getting the tree data

### ISSUE THREAD

**Issue by SagarYVM** [khan4019/tree-grid-directive#25]
Hi Khan,
Thanks for your effort in building tree grid and sharing!!! 
This is what exactly I am looking for. But unfortunately, Its not working in my .Net project. We are using AngularJS 1.3.0-beta.18 version. The problem is its not able to get the Tree data & Column definitions from my application scope. Any thoughts?
-Sagar

**Comment by diosney** [comment]
It is very likely it doesn't has to be with Angular nor .NET specifically.

I'm using 1.3.11 version and it works fine, so maybe its the configuration, the way you are passing the data or so.

Maybe you can post some data so we can help you or tell if the module author can close the issue?

Thanks

**Comment by ImranAppdev** [comment]
Hello Khan,


I also tried to implement the same and exactly followed the steps given with your sample  and also with my data. In ui it just binds table headers.


Assigning scope variable ,
 $scope.tree_data = [
    {
        Name: "USA", Area: 9826675, Population: 318212000, TimeZone: "UTC -5 to -10",
        children: [
          {
              Name: "California", Area: 423970, Population: 38340000, TimeZone: "Pacific Time",
              children: [
                  { Name: "San Francisco", Area: 231, Population: 837442, TimeZone: "PST" },
                  { Name: "Los Angeles", Area: 503, Population: 3904657, TimeZone: "PST" }
              ]
          },
          {
              Name: "Illinois", Area: 57914, Population: 12882135, TimeZone: "Central Time Zone",
              children: [
                  { Name: "Chicago", Area: 234, Population: 2695598, TimeZone: "CST" }
              ]
          }
        ]
    },
 { Name: "Texas", Area: 268581, Population: 26448193, TimeZone: "Mountain" }
    ];

Binding tree in html,
<tree-grid tree-data="tree_data"></tree-grid>

Just grid headers alone getting displayed for me . the data rows are not displayed. Any idea why ?

**Comment by TrueDub** [comment]
@ImranAppdev is this still outstanding? Will close due to age if not.

**Comment by pcr1393** [comment]
Whenever I change the data in tree_data variable and assign new key value pairs, the headers are not changing and the new values are not getting mapped? Can someone pls suggest what is wrong here and what changes should i make ?
