### ISSUE TITLE
Sorting data

### ISSUE THREAD

**Issue by kotmatpockuh** [khan4019/tree-grid-directive#26]
Hi.

Seems that there is some stange behaviour with sorting:

<tr ng-repeat=\"row in tree_rows | orderBy:Pos...

but how to be, if node has leafs with such key Pos too? how to sort branches and leafs of branch via exaclty same field so that nodes are sorted via field, and branches are sorted only in scope of it's parent?

**Comment by diosney** [comment]
I need this functionality too. I don't promise anything, but in the next weeks I will try to add this feature.

To clarify, what you are asking for is:

- Initially load the tree with custom tree_data
- Then click in a column header to sort data asc or desc
- Afterward another click in the same column just toggle the sort order

And the tree data will be sorted by that column, with the specified sort order (asc or desc) for all tree levels, as:

Example of an asc sort order if the column was clicked:

```js
a
     1
          i
          ii
     2
     3
b

**Comment by khan4019** [comment]
+1

**Comment by TrueDub** [comment]
Sorting of columns now added in the latest pull request
