### ISSUE TITLE
Only 1st column "Name" is showing up, other columns ignored

### ISSUE THREAD

**Issue by pprotim** [khan4019/tree-grid-directive#36]
Hi,
I am new to angular js. I was exactly looking similar to tree-grid-directive. Thank you for the tree-grid directive. But I am facing a strange issue. When I mode the raw data code for the example in treeGridTest.js file is moved under a function (submitForm) then I  do not get all the columns back, instead it is only showing 1st column. I have modified the treeGridTest.js and treeGrid.html to treeGrid.jsp ( just to work with jsp, and added a submit button). Please see the result in  output.png
![output](https://cloud.githubusercontent.com/assets/11229718/6413078/7de5f24e-beb1-11e4-9fa8-47cc9793a76d.PNG)
Changes for treeGridTest.js  is as below:

 app.controller('treeGridController', function ($scope, $timeout) {
       var tree;
        $scope.tree_data = [];---->added this line
        $scope.submitForm = function() {--- added this line
        	
        	var rawTreeData = [
        	                   {
        	                       "DemographicId": 1,
        	                       "ParentId": null,
        	                       "Name": "United States of America",
        	                       "Description": "United States of America",
        	                       "Area": 9826675,
        	                       "Population": 318212000,
        	                       "TimeZone": "UTC -5 to -10"
        	                   },
....
.....
...... rest of the code remains same here
}//closure of function submitForm 
}//closure of controller treeGridController..

===================================================================
Changes in treeGrid.jsp (which was originally treeGrid.html fiile)

<div ng-show="showMinDir">
            <strong>bare minimum directive:</strong> <code>&lt;tree-grid tree-data="tree_data"&gt;&lt;/tree-grid&gt;</code>
            <br/>
            <br/>
            <tree-grid tree-data="tree_data"></tree-grid>
        </div>
============added button from a form starts=============
         &lt;form name="myForm"&gt;
	    	&lt;button type="button" class="btn btn-primary" data-ng-click="submitForm(myForm)"&gt;Submit&lt;/button&gt;
	    </form>"
=============added button from a form ends===============

==============================================================
Could you please guide me where I am doing the mistake or what changes I need to do the correction?

Thanks
Partha.

**Comment by magiccrafter** [comment]
Try adding the following in your Controller:
```javascript
$scope.col_defs = [
    { field: "Area" }
];
```
Then your directive should be used as:
```javascript
<tree-grid tree-data="tree_data" col-defs="col_defs"></tree-grid>
```
This should give you the basic idea.

**Comment by pedro-mass** [comment]
what @magiccrafter fixed the issue for me as well

**Comment by TrueDub** [comment]
Closing as solution present.
