### ISSUE TITLE
In `cellTemplate` allow for outer scope methods utilization

### ISSUE THREAD

**Issue by diosney** [khan4019/tree-grid-directive#37]
When defining the `cellTemplate` value, it can be usefull to have access to the controller scoped methods, that way we can further format the value in the cell template.

@khan4019 I will work in this issue in the coming weeks (not now) since its useful for me, once I finish I will make a PR, I opened the issue just to let you know.

**Comment by pauloafons** [comment]
+1 for this. is a nice feature to implement!!
