### ISSUE TITLE
Search in Treegrid

### ISSUE THREAD

**Issue by gauravsaini03** [khan4019/tree-grid-directive#45]
Hello @khan4019 

Thanks for making this awesome plugin, it has make our life easier.
Actually, I was thinking about the search to be implemented. As, no tree grid plugin offer filters, sorting etc.

Thanks
Gaurav

**Comment by khan4019** [comment]
why dont u implement this and share with us

**Comment by gauravsaini03** [comment]
@khan4019 : I have done it other way, I have injected the same data in as a search filter in my angular-template. :)
Will try to do it outofbox and will share.

**Comment by khan4019** [comment]
plz do

**Comment by TrueDub** [comment]
This functionality is now added in the latest pull request
