### ISSUE TITLE
Custom function for sorting 

### ISSUE THREAD

**Issue by seshur** [khan4019/tree-grid-directive#63]
Hi Team,
Thanks for providing the treeGrid, control is really very helpful and and easy to use as well. I have used this treeGrid for achieving my requirement where everything i was able to achieve except implementing custom sorting function. 
I need to call my local scope function on sort click to make a call to my service to receive the data.

Can you please help me here like how can i achieve this using this treeGrid.

Thanks,
Seshu.

**Comment by Rovak** [comment]
@seshur should be fixed in #64

**Comment by TrueDub** [comment]
Closed as fixed
