### ISSUE TITLE
How to fix width for each column

### ISSUE THREAD

**Issue by sundertinwar** [khan4019/tree-grid-directive#65]
How can I fix width for each column? And alternatively can I set column width according to content?

Is it possible to not to show column header?

How to set alternative row styling?

From your example http://khan4019.github.io/tree-grid-directive/test/treeGrid.html here. If I want to change column Name display name to Country Name without touching JSON. How can we do this? If I add Name column in display column list, it display name column twice.

How column headers are formatted in your example?

Thanks

**Comment by torsten-sauer** [comment]
In all cases you can use an own template. Start with copying the original one and modify as needed.
To remove the headers, remove the th-tags in the template, to set width of column add classes or numbers or what you like to the data and use this inside the ng-repeat. You can also use fixed columns (not that flexible, but possible).

The first column is special, you need to override it inside the `expand-on` property. It will be shown twice if you add it to the `col-defs`

**Comment by TrueDub** [comment]
Closing as an answer is in place.
