### ISSUE TITLE
How do i Remove leaf icon ?

### ISSUE THREAD

**Issue by shah-bhavesh** [khan4019/tree-grid-directive#67]
as i m getting default "+" for parent and page icon for leaf , how do remove or modify them please help

**Comment by vivek-dhayalan** [comment]
Would be great if you could tell how you did it.

**Comment by vivek-dhayalan** [comment]
Figured out by myself posting the same so that it may help some one in future
 <tree-grid tree-data="tree_data" col_defs="col_defs" icon-leaf = "none"></tree-grid>
