### ISSUE TITLE
Slow performance of tree grid for large json.

### ISSUE THREAD

**Issue by IamTejasPatel** [khan4019/tree-grid-directive#75]
I am facing considerable lag in select/deselect , collapse/expend tree etc. I have attached json file , can you provide me work around. Also I have attached  my tree grid screenshot.

[data.zip](https://github.com/khan4019/tree-grid-directive/files/70576/data.zip)

**Comment by sumedhkalaskar** [comment]
facing the same issue for 5000+ array size. it stop expanding tree and throw script error.

**Comment by TrueDub** [comment]
This would be caused by the sheer size of your arrays - Angular's two-way binding is slow with datasets of that size. I'm not sure a workaround is possible.

**Comment by TrueDub** [comment]
closing due to lack of further update
