### ISSUE TITLE
sortable expanding_property

### ISSUE THREAD

**Issue by miguelcamargo9** [khan4019/tree-grid-directive#79]
I want to sort the field by which the shaft extends , as I can do this without adding the field to the definition of columns?

**Comment by beardedinbinary** [comment]
Anyone figure out a work around for this? I can't seem to get the expandingProperty column to also be sortable. This is a huge problem.

**Comment by TrueDub** [comment]
By sortable, I presume you mean the user can reorder the expandable property column after rendering. If so, this is already available, simply by adding sortable: true to your expanding property object, as follows:

```
vm.expandingProperty = {
                        field: 'text',
                        displayName: 'Directory or File',
                        sortable: true,
                        filterable: true
                    };
```
Does this cover what you're asking about?

**Comment by TrueDub** [comment]
Closing as a fix is in place.
