### ISSUE TITLE
Create a release to allow the directive be imported via Bower

### ISSUE THREAD

**Issue by TrueDub** [khan4019/tree-grid-directive#87]
Could you create a release please? This will allow the code be managed via Bower, rather than manually.

**Comment by TrueDub** [comment]
I'm really looking to get this project published on NPM, to allow it be used as a dependency there. Could someone tell me if that's a possibility in the next while, in which case I'll submit a pull request with a couple of new features and the relevant work for NPM.

Judging by the issues log and in particular the pull requests log, it appears that there isn't much being done, so if that's the case I'll publish my fork on NPM instead, under a different name, but with all credit given to this project.

Should this project be published on NPM subsequently, I'll deprecate mine, but I need to get this on NPM and if it can't be done this way, I'll have to do it myself.

**Comment by khan4019** [comment]
why not send a PR to this project here. and be a contributor

**Comment by TrueDub** [comment]
I have already done so, last year. My concern is that there are outstanding pull requests and it didn't seem that the project is maintained. If this is not the case, and you'll publish to NPM (and create a release on github) I'll gladly send a PR to provide some functionality updates, plus things needed for the NPM release.

**Comment by khan4019** [comment]
awesome...looking forward to it

**Comment by TrueDub** [comment]
Pull request #96 raised to cover NPM changes - instructions for publishing are at [https://docs.npmjs.com/getting-started/publishing-npm-packages](https://docs.npmjs.com/getting-started/publishing-npm-packages)

**Comment by TrueDub** [comment]
As you've now added me as an contributor (many thanks) would you like me to do the release stuff?

**Comment by khan4019** [comment]
Please go ahead. and feel free to add any new feature

**Comment by TrueDub** [comment]
Done now - and readme updated. Going to close this issue now. Thank you.

**Comment by khan4019** [comment]
Fantastic

*MD Khan | Sr. Web Developer*

Nielsen

Chicago, IL 60201

(p) 701.412.4019 |  www.thatjsdude.com
