### ISSUE TITLE
How can you dynamically add Checkbox  colums? 

### ISSUE THREAD

**Issue by nainakela** [khan4019/tree-grid-directive#93]
Hello,
How can you dynamically add checkbox colums?

**Comment by grisha1776** [comment]
Hi, 
I had to modify the tree-grid do do this. I've added additional parameter to directive "hide-checkboxes": 
   	<tree-grid tree-data="clientTreeData"
		col-defs="treeCtrl.clientTreeColDefs"
		expand-on='treeCtrl.clientTreeExpandingDef' 
                expand-level="2"
		tree-control="treeCtrl"
		viewable-tree='treeCtrl.viewableTree'
		search="treeCtrl.search"
		hide-checkboxes="true">
in tree-grid.js as follows:
scope : {
										direction : '@',
										treeData : '=',
										colDefs : '=',
										expandOn : '=',
										onSelect : '&',
										onClick : '&',
										initialSelection : '@',
										treeControl : '=',
										search : '=',
										hideCheckboxes: '='
									},
also in tree-grid.template.html:
	<tbody>
			<tr
				ng-repeat="row in tree_rows | searchFor:search.text:expandingProperty:colDefinitions track by row.branch.uid"
				class="tree-grid-row">
				<td ng-hide="hideCheckboxes">
					<input type="checkbox" ng-model="row.branch.isChecked">
				</td>
