### ISSUE TITLE
Different versions of "tree-grid-directive.js"

### ISSUE THREAD

**Issue by mpd-dude** [khan4019/tree-grid-directive#95]
Hi all, 

it seems that there are two different versions of the file "tree-grid-directive.js" in use:

1) Source:
https://github.com/khan4019/tree-grid-directive/blob/master/src/tree-grid-directive.js

2) In use in the live example
http://khan4019.github.io/tree-grid-directive/src/tree-grid-directive.js

Is there a reason for this or is it an oversight?

**Comment by TrueDub** [comment]
@khan4019 - could you have a look at updating the code on the github.io page to version 0.2.0 please?

**Comment by khan4019** [comment]
Done

**Comment by TrueDub** [comment]
Excellent, thank you. Closing this.
